kit:
  name: "Qubell Selenium Grid"
  link: https://github.com/qubell/component-selenium-grid
  applications: 
    - name: "Selenium Grid"
      manifest: "https://raw.github.com/qubell/component-selenium-grid/master/selenium-grid-manifest.yml"
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: ""
